algoritmo ejercicio_2
//1.DESCRIPCION DEL PROLEMA A PROGRAMAR

//2.DECLARACION DE VARIABLES Y CONSTANTES
//3.IDENTIFICACION DE VARABLES Y CONSTANTES
//4.DECOLECCION DE DATOS
//5.PROCESAMIENTO DE LA INFORMACION
//6.VISUALIZACION DE LOS RESULTADOS
fin algoritmo
