algoritmo ejercicio_3

//1.DESCRIPCION DEL PROLEMA A PROGRAMA QUE

//HALLAR UNO DE LOS LADOS DE UN RECTANGULO CUYA AREA ES DE 15 CM2 Y UNO DE SUS LADOS MIDE 3CM

//2.DECLARACION DE VARIABLES Y CONSTANTES
definir area,n,m como real;
//3.IDENTIFICACION DE VARABLES Y CONSTANTES
area<-0;
n<-3;
m<-0;
//4.DECOLECCION DE DATOS
//5.PROCESAMIENTO DE LA INFORMACION
m<-area/n;
//6.VISUALIZACION DE LOS RESULTADOS
escribir "el valor de el lado faltante es de ",m;
fin algoritmo
