Algoritmo sin_titulo
	//1.DESCRIPCION DEL PROLEMA
    //
	//2.DECLARACION DE VARIABLES Y CONSTANTES
	definir i,j como entero;
	//3.IDENTIFICACION DE VARABLES Y CONSTANTES
    i<-0;
	j<-0;
	//4.DECOLECCION DE DATOS

	//5.PROCESAMIENTO DE LA INFORMACION
	
	//6.VISUALIZACION DE LOS RESULTADOS
	
FinAlgoritmo
